{{- $fluxSettingsCloudbees := merge .Values.addons.cloudbees.flux .Values.flux -}}
{{- if .Values.addons.cloudbees.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudbees
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cloudbees
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}

spec:
  releaseName: cloudbees
  targetNamespace: cloudbees
  chart:
    spec:
      chart: {{ .Values.addons.cloudbees.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: cloudbees
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsCloudbees | nindent 2 }}
  
  {{- if .Values.addons.cloudbees.postRenderers }}
  postRenderers:
  {{ toYaml .Values.addons.cloudbees.postRenderers | nindent 4 }}
  {{- end }}  
  valuesFrom:
    - name: {{ .Release.Name }}-cloudbees-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-cloudbees-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-cloudbees-values
      kind: Secret
      valuesKey: "overlays"

  values:

  {{- if or .Values.gatekeeper.enabled .Values.istio.enabled .Values.monitoring.enabled }}
  dependsOn:
  {{- if .Values.gatekeeper.enabled }}
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.istio.enabled }}
    - name: istio
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
{{- end }}
