{{- if .Values.cloudbees.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: cloudbees
  labels:
    app.kubernetes.io/name: cloudbees
    app.kubernetes.io/component: "devloper-tools"
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: enabled
{{- end }}