{{- if .Values.cloudbees.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.cloudbees "name" "cloudbees" "defaults" (include "bigbang.defaults.twistlock" .)) }}
{{- end }}

{{- define "bigbang.defaults.cloudbees" -}}
# hostname is deprecated and replaced with domain. But if hostname exists then use it.
{{- $domainName := default .Values.domain .Values.hostname }}
hostname: {{ $domainName }}
domain: {{ $domainName }}

imagePullSecrets:
- name: private-registry

istio:
  enabled: {{ .Values.istio.enabled }}
  console:
    gateways:
    - istio-system/{{ default "public" .Values.cloudbees.ingress.gateway }}

{{- if .Values.istio.enabled }}
annotations:
  {{ include "istioAnnotation" . }}
{{- end }}

{{- end -}}
